services:
  # MongoDB
  mongo:
    image: mongo:latest
    container_name: harvest_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - harvest_network
    restart: always

  # Redis
  redis:
    image: redis:alpine
    container_name: harvest_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - harvest_network
    restart: always
    command: redis-server --appendonly yes
    
  # RabbitMQ With Management Plugin
  # Visit management web portal: http://localhost:15672/#/queues (admin, password credentials)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: harvest_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - harvest_network
    restart: always

networks:
  harvest_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: